// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noxgkoypyszhekqbepel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5veGdrb3lweXN6aGVrcWJlcGVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDM2NTcsImV4cCI6MjA3MzQxOTY1N30.i2B0obca_v-2ZrPBM0_uInIUGe1odBJEKBrg0RnlqgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});